// import _ from 'lodash'
// import './styles/style.css'
import './styles/style_300x600.css'
import './styles/style_miraclex1440x250_animation.css'
import './styles/style_miraclex1440x250_keyframes.css'
